### PR TITLE
Add types declaration file

### LINKED ISSUE #1: TypeScript type declaration file
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

### PR DESCRIPTION
**Pull request by geopic**
Resolves #1. Let me know if there are any issues.

### CODE REVIEW

**Comment by iColtz** [comment]
> Resolves #1. Let me know if there are any issues.

The SkyBlock interface should have a `_fetch` function property.
Seen here: https://github.com/iColtz/node-hypixel.js/blob/main/src/lib/HypixelClient.js#L33

**Comment by geopic** [comment]
I deliberately left that and other methods prefaced with an underscore out @iColtz as they're intended to be private and (as far as I know) you can't set properties of an interface to be private.

**Comment by iColtz** [comment]
> I deliberately left that and other methods prefaced with an underscore out @iColtz as they're intended to be private and (as far as I know) you can't set properties of an interface to be private.

Yes the `_fetch` method was intended to be private, I wasn't aware that properties of an interface couldn't be private. Merging now.

**Comment by geopic** [comment]
Lovely, thanks man. 😄

**Pull request merged**
